// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://longchcfhlvsngvvmssa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvbmdjaGNmaGx2c25ndnZtc3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMTM0MjMsImV4cCI6MjA2OTY4OTQyM30.y3-DEIT_7zcSvZzUkkqqZPx2SexiQsqc2nIiH8_reQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});